CREATE TABLE IF NOT EXISTS PRODUCTS(
    PRODUCT_ID TEXT PRIMARY KEY,
    PRODUCT_NAME TEXT,
    PRODUCT_PRICE INTEGER,
    PRODUCT_COMMISSION INTEGER
);

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_COMMISSION) VALUES
('P001', 'ACI Salt 1kg', 50, 5),
('P002', 'PRAN Mango Juice 1L', 120, 10),
('P003', 'Fresh Soybean Oil 5L', 750, 20),
('P004', 'Bashundhara Tissue', 30, 3),
('P005', 'Molla Super Rice 25kg', 1600, 50),
('P006', 'Teer Flour 2kg', 110, 8),
('P007', 'Square Toiletries Soap', 45, 4),
('P008', 'PRAN Tomato Sauce 500ml', 90, 7),
('P009', 'ACI Pure Spices (Chili) 200g', 80, 6),
('P010', 'Radhuni Masala Pack', 60, 5);

SELECT * FROM PRODUCTS

SELECT * FROM PRODUCTS WHERE PRODUCT_PRICE = (SELECT MIN(PRODUCT_PRICE) FROM PRODUCTS AS MIN_PRICE)

SELECT * FROM PRODUCTS WHERE PRODUCT_PRICE = (SELECT MAX(PRODUCT_PRICE) FROM PRODUCTS)

SELECT MIN(PRODUCT_PRICE) AS MIN_PRICE FROM PRODUCTS
SELECT MAX(PRODUCT_PRICE) AS MAX_PRICE FROM PRODUCTS

UPDATE PRODUCTS SET PRODUCT_PRICE = 1500, PRODUCT_COMMISSION = 40 WHERE PRODUCT_ID = 'P005';

SELECT * FROM PRODUCTS

DELETE FROM PRODUCTS WHERE PRODUCT_ID = 'P010';
